# Generated by Django 4.2.7 on 2023-12-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customadmin",
            name="telegram_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
