# Generated by Django 4.2.7 on 2023-12-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customadmin",
            name="region",
            field=models.CharField(
                choices=[
                    ("Andijon", "Andijon"),
                    ("Buxoro", "Buxoro"),
                    ("Farg'ona", "Farg'ona"),
                    ("Jizzax", "Jizzax"),
                    ("Xorazm", "Xorazm"),
                    ("Namangan", "Namangan"),
                    ("Navoiy", "Navoiy"),
                    ("Qashqadaryo", "Qashqadaryo"),
                    ("Samarqand", "Samarqand"),
                    ("Sirdaryo", "Sirdaryo"),
                    ("Surxandaryo", "Surxandaryo"),
                    ("Toshkent", "Toshkent"),
                    ("Toshkent shahar", "Toshkent shahar"),
                    ("Qoraqalpog'iston", "Qoraqalpog'iston"),
                ],
                default="Belgilanmagan",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subregion",
            field=models.CharField(default="asdasd", max_length=150),
        ),
    ]
