# Generated by Django 4.2.7 on 2023-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_customadmin_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customadmin",
            name="region",
            field=models.CharField(
                choices=[("Namangan", "Namangan")], default="nanna", max_length=200
            ),
        ),
    ]
