# Generated by Django 4.2.7 on 2023-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_answer_category_faq_question_user_delete_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=200),
        ),
    ]
