# Generated by Django 4.2.7 on 2023-12-06 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_customadmin_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customadmin",
            name="region",
        ),
    ]
