# Generated by Django 4.2.7 on 2023-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_faq_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.BooleanField(
                choices=[("Yes", "Yes"), ("No", "No")], default=False
            ),
        ),
    ]
