# Generated by Django 4.2.7 on 2023-12-07 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_customadmin_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Javob ", "verbose_name_plural": "Javoblar "},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "yo'nalish ",
                "verbose_name_plural": "Yo'nalishlar ",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "verbose_name": "faq ",
                "verbose_name_plural": "Ko'p beriladigan savollar ",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "savol ", "verbose_name_plural": "Savollar "},
        ),
        migrations.AlterModelOptions(
            name="regions",
            options={"verbose_name": "hudud ", "verbose_name_plural": "Hududlar "},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "xodim ", "verbose_name_plural": "Xodimlar "},
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="\n            Telefon raqam quyidagi formatda kiritish kerak: '+9981234567'. \n            15 ta raqamgacha ruxsat berilgan.\n        ",
                        regex="^\\+\\d{8,15}$",
                    )
                ],
            ),
        ),
    ]
