# Generated by Django 4.2.7 on 2023-12-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_question_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(default="asda", max_length=60),
        ),
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
