# Generated by Django 4.2.7 on 2023-12-07 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_answer_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customadmin",
            name="region",
        ),
    ]
